### ISSUE TITLE
Ticking Entity in Nether Causing World to Become Unusable

### ISSUE THREAD

**Issue by OnTarasMind** [thephoenixlodge/Heavens-of-Sorcery#103] opened 2020-09-19 10:07 UTC
[**Crash report is here**](https://pastebin.com/VB2kaHzc)

Presumably, this crash has something to do with zombie pigman aggro, but I'm not sure if this is entirely a vanilla issue, so I figured it would be best to report this here in the case that this is an issue with a mod that is changing pigman behavior or is conflicting with their behavior in some way, shape or form.

I managed to get the game difficulty switched over to peaceful and back, which seems to have fixed the crash loop, which is done via alt-tabbing while loading in, causing the pause menu to immediately come up, which allowed me to switch the game to peaceful.

**Comment by ewanm89** [comment] 2020-09-23 15:44
duplicate of #68

**Closed** 2022-01-26 23:46 UTC
